### ISSUE TITLE
Class Support

### ISSUE THREAD

**Issue by GLanguage** [XingZiLong/class-method-anonymous_function#1]
Hello.

**Comment by XingZiLong** [comment]
Hello. (Feeling Strange)

**Comment by XingZiLong** [comment]
We are talking about ```function(){...}```, right?

**Comment by XingZiLong** [comment]
Oh! It works!
I input ```施「」於「console.log(0)」``and it compiles into ``const _ans1 = (console.log(0))```

**Comment by XingZiLong** [comment]
What about ```施「」於「function(){var a = 0; console.log(a);}」。```?

Wow! It really works! It compiles into 
```
const _ans1 = (function(){
   var a = 0;
   console.log(a)
})```
And if I add ```施「_ans1」。```, it outputs 0!

**Comment by GLanguage** [comment]
投机取巧最终还是战胜了中规中矩。

**Comment by GLanguage** [comment]
现在你可以写一个package，把这些投机取巧的东西封装起来（就像脚本秘术一样，那个也很投机取巧），然后创造代码可读性。

**Comment by XingZiLong** [comment]
投機取巧。。。比那個   ```施「function」於「){甲}(」```  好多了（也有用多了）

**Comment by XingZiLong** [comment]
我試一下

**Comment by GLanguage** [comment]
可我的class还是毫无头绪。如果解决了那个问题，那么所有的问题就都迎刃而解了。

**Comment by XingZiLong** [comment]
嗯

**Comment by XingZiLong** [comment]
那個問題？

**Comment by XingZiLong** [comment]
我覺得我們可以直接檢查文言代碼

**Comment by GLanguage** [comment]
现在我的需求是，要找到一种方法，在`a`已知的情况下得到函数`g(a)`使其与`f(a)`具有同样的效果。

**Comment by XingZiLong** [comment]
你是说 ```g() = f(a)``` ，也就是 ```g() = function(){return f(a)}``` 吗？
我刚刚也在说这个问题。
```施「」於「function(){return f(a)}」。名之曰「甲」。施「甲」。``` 應該是可以的
我也在琢磨，但是现在没什么时间

**Comment by GLanguage** [comment]
我有过这个想法，但有个问题不知道你能不能解决：
如果有`f(a)`，那么`g = function() {return f(a)}`就可以；
但是如果有`f(a)(b)`，那么`g = function(b) {return f(a)}`才行；
如果有`f(a1)(a2)(...)(an)`，那么`g`的定义就会非常尴尬，因为不知道n是多少。

**Comment by XingZiLong** [comment]
你可以试一下柯里化（参考柯里化法package的源码，上网搜也有），就是你可以先定义f0(a1,a2,a3,...,an)，再通过柯里化变成f(a1)(a2)(a3)...(an)，但是用f0来定义g。JS 里面应该有arguments，就是所有参数组成的array，可以试试。

**Comment by XingZiLong** [comment]
只是过程非常复杂，你可以先用JS编好再慢慢转成文言

**Comment by XingZiLong** [comment]
我可能没说清楚，我在说一下。
先定义 ```f0(a1,a2,a3,a4,...,an)``` 。
再定义 ```f(a1)(a2)(a3)...(an) = f0(a1,a2,a3,a4,...,an)``` 。
再用 ```f0()``` 来定义 ```g``` ， ```function g() {return f0()}``` 。
我的「连加连乘」也用了这种方法，可以参考一下

**Comment by GLanguage** [comment]
Hello. I have something GREAT to tell you.
1. I found a *solution* to the bug in the class package: do `f(self)` first, and use `typeof`. If it is a function (that it is multiple-argument) , then add it to the class. Otherwise (that it has only one argument `self`) , create a new function `function() { return f(self) }` and add it to the class.
2. The solution above needs your `typeof` package, and I noticed that “夫「甲」之類” is only a macro of `typeof`, that means the string it returns will be like `"function"`, `"number"` and etc (in English) . If we add these strings to the wenyan code, it will be strange. In order to write the code in pure wenyan, you may change the strings into wenyan like "function" to “術”, "string" to “言”, etc. I can help you if you need.

**Comment by GLanguage** [comment]
Moreover, remove the `hard to fix` label. It is not 'hard to fix' any more. :P

**Comment by XingZiLong** [comment]
Wow. It _**IS**_ great. But I soon realize that we already have 「識類」in 「格物」. (「格物第十」in 「文言陰符」). Really bad.

**Comment by XingZiLong** [comment]
You can fork this (I really want you to do this, because the idea is yours) and create a pr about your changes.

**Comment by GLanguage** [comment]
> I found a solution to the bug in the class package: do f(self) first, and use typeof. If it is a function (that it is multiple-argument) , then add it to the class. Otherwise (that it has only one argument self) , create a new function function() { return f(self) } and add it to the class.

殆矣。陋之甚。若先行`f(self)`，则已执行矣。得术则已，不得术岂不已执行哉？
若
```
吾有一術。名之曰「報名」。欲行是術。必先得一物。曰「己」。乃行是術曰。
    夫「己」。夫「「名」」。取二以施「取物」。加其於「「吾乃」」。加其以「「也。」」。書之。
是謂「報名」之術也。
```
行`f(self)`，则书
```
吾乃禽也。
```
呜呼！

**Comment by GLanguage** [comment]
Add `hard to fix` again? :-(

**Comment by XingZiLong** [comment]
That’s really bad. I think we are going back to the origin — we have the problem from the start, but still we don’t fix it.

**Comment by XingZiLong** [comment]
We can look at the compiled JS. Can you make a screenshot of your compilation?

**Comment by GLanguage** [comment]
Main part about `法`.
```javascript
          var _ans10 = 法書
          var _ans11 = 法名
          var _ans12 = 取物(_ans10)(_ans11)
          var 外法 = _ans12
          var _ans13 = 外法(此)
          var 類法 = _ans13
          var _ans14 = 識類(類法)
          if (_ans14 == "術") {
            var _ans15 = 此
            var _ans16 = 法名
            var _ans17 = 類法
            var _ans18 = 置物(_ans15)(_ans16)(_ans17)
          } else {
            var 無參類法 = () => 0
            無參類法 = function() {
              var _ans19 = 外法(此)
              return _ans19
            }
            var _ans20 = 此
            var _ans21 = 法名
            var _ans22 = 無參類法
            var _ans23 = 置物(_ans20)(_ans21)(_ans22)
          }
```

**Comment by GLanguage** [comment]
In `var _ans13 = 外法(此)`, if `外法` is like `function(self) { console.log( ... ) }` then it will output the `...` part when we call `施「生鳥」。名之曰「鳥」。`

**Comment by XingZiLong** [comment]
Maybe you can check this one:
The reason of the problem can be one of them below:
- ```function(){...}()``` will execute the function directly, because it have an ```()``` after it .
- the function don’t return a function, but return ```void```, and you write the function inside your function body.
- more...

**Comment by GLanguage** [comment]
I probably can raise an issue in wenyan-lang/wenyan repo and ask for solution.

**Comment by XingZiLong** [comment]
Absolutely, and this question is far more simple and accurate.

**Comment by GLanguage** [comment]
你还是赶紧把`施「」於「function(){ ... }」。`发到`wyg`上造福大众吧。

**Comment by XingZiLong** [comment]
算了吧，留着自己用，不要破坏文言语言中规中矩的特性 :) :D :P :B

**Comment by XingZiLong** [comment]
Ah, I can’t help you this time. I’ll delete this repo and goodbye.
